baseURL = 'https://chullepg.github.io'
languageCode = 'en-us'
title = 'CHull website'
theme = 'notrack'

[params]
author = 'Chris Hull'
# optional, defaults to author:
siteHeading = 'Chris Hull website'
mainSections = ['blog']